/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Alumno;

//import java.awt.Event;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import javax.swing.JOptionPane;
//import java.sql.DriverManager;
//import java.sql.SQLException;
//import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.KeyStroke;

/**
 *
 * @author jose6
 */
public class CAlumno extends javax.swing.JFrame {
    String msj1,msj2;
    Statement stmt=null;
    /**
     * Creates new form CAlumno
     */
    
    public CAlumno() {
        initComponents();
        this.setTitle("Consultar, Modificar y Eliminar Alumno");
        this.setLocationRelativeTo(null);
        //cmb_opc.setVisible(false);
        
              Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
      int height = pantalla.height;
      int width = pantalla.width;
      setSize(width/2, height/2);		

      setLocationRelativeTo(null);		
      setVisible(true);
        setLocationRelativeTo(null);
        setSize(900,668);
        setTitle("UDG");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_ncontrol = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apaterno = new javax.swing.JTextField();
        txt_amaterno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        cmb_semestre = new javax.swing.JComboBox<>();
        cmb_turno = new javax.swing.JComboBox<>();
        cmb_grupo = new javax.swing.JComboBox<>();
        cmb_status = new javax.swing.JComboBox<>();
        b_modificar = new javax.swing.JButton();
        lbl_foto = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton1.setText("Numero de control");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton1KeyTyped(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(710, 70, 147, 76);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Consultar");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(410, 30, 120, 31);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Numero de Control");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 273, 190, 30);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 330, 120, 23);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Apellido Paterno");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 380, 170, 23);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Apellido Materno");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 430, 170, 23);

        txt_ncontrol.setEditable(false);
        txt_ncontrol.setEnabled(false);
        txt_ncontrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ncontrolActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ncontrol);
        txt_ncontrol.setBounds(30, 300, 260, 30);

        txt_nombre.setEnabled(false);
        getContentPane().add(txt_nombre);
        txt_nombre.setBounds(30, 350, 260, 30);

        txt_apaterno.setEnabled(false);
        getContentPane().add(txt_apaterno);
        txt_apaterno.setBounds(30, 400, 260, 30);

        txt_amaterno.setEnabled(false);
        getContentPane().add(txt_amaterno);
        txt_amaterno.setBounds(30, 450, 260, 30);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setText("Semestre");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(640, 330, 180, 20);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setText("Grupo");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(640, 380, 170, 20);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setText("Turno");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(640, 270, 160, 20);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setText("STATUS");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(640, 430, 180, 20);

        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(530, 550, 120, 30);

        cmb_semestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "1", "2", "3", "4", "5", "6" }));
        cmb_semestre.setEnabled(false);
        getContentPane().add(cmb_semestre);
        cmb_semestre.setBounds(580, 350, 270, 30);

        cmb_turno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "MATUTINO", "VESPERTINO", "????" }));
        cmb_turno.setEnabled(false);
        cmb_turno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_turnoItemStateChanged(evt);
            }
        });
        cmb_turno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_turnoActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_turno);
        cmb_turno.setBounds(580, 290, 270, 30);

        cmb_grupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "A", "B" }));
        cmb_grupo.setEnabled(false);
        cmb_grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_grupoActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_grupo);
        cmb_grupo.setBounds(580, 400, 270, 30);

        cmb_status.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cmb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "Activo", "Inactivo" }));
        cmb_status.setEnabled(false);
        getContentPane().add(cmb_status);
        cmb_status.setBounds(580, 450, 270, 30);

        b_modificar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        b_modificar.setText("Modificar");
        b_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(b_modificar);
        b_modificar.setBounds(390, 550, 118, 30);

        lbl_foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_foto);
        lbl_foto.setBounds(70, 50, 170, 190);

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 550, 120, 30);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo menu.jpg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 900, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   void limpiar(){
       txt_ncontrol.setText("");
       txt_nombre.setText("");
       txt_apaterno.setText("");
       txt_amaterno.setText("");
       
   }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        ResultSet rs=null;
        
        msj1=JOptionPane.showInputDialog(this, "Numero de control","Consultar alumno",JOptionPane.QUESTION_MESSAGE);
        String sql="SELECT * FROM alumno WHERE NControl ='"+msj1+"'";
        //String sql1="Select * from calis where usuario=? and contra=?";
        
        if (msj1==null)
            JOptionPane.showMessageDialog(this, "La opcion fue cancelada","Aviso!",JOptionPane.INFORMATION_MESSAGE);
        else{
            if(msj1.equals("")){
                JOptionPane.showMessageDialog(this, "Ingrese el NUMERO DE CONTROL del alumno que desea consultar","Aviso!",JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/udg","root","");
                    stmt=con.createStatement();
                    rs=stmt.executeQuery(sql);
                    
                    
                    if (rs.next()){
                        //imagen
                        Imagen imagen=new Imagen();
                        Blob blob = rs.getBlob("imagen");
                        byte[] data = blob.getBytes(1, (int)blob.length());
                        BufferedImage img = null;
                        try {
                            img = ImageIO.read(new ByteArrayInputStream(data));
                            } catch (IOException ex) {
                           
                            }
                        imagen.setImagen(img);
                        int ancho= lbl_foto.getWidth();
                        int alto= lbl_foto.getHeight();
                        Icon icon = new ImageIcon(imagen.imagen.getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
                        lbl_foto.setIcon(icon);
                        
                        //----------------------
                        
                        txt_ncontrol.setText(rs.getString("NControl"));
                        txt_nombre.setText(rs.getString("NAlumno"));
                        txt_apaterno.setText(rs.getString("APAlumno"));
                        txt_amaterno.setText(rs.getString("AMAlumno"));
                        cmb_turno.setSelectedItem(rs.getString("TAlumno"));
                        cmb_semestre.setSelectedItem(rs.getString("SAlumno"));
                        cmb_grupo.setSelectedItem(rs.getString("GAlumno"));
                        cmb_status.setSelectedItem(rs.getString("VAlumno"));
                        //byte[] lbl_foto=rs.getBytes("nomImagen");
                        try{
                            
                        }catch(Exception ex){
                            
                        }
                    }
                    else {
                        JOptionPane.showMessageDialog(null,"No existe ese numero de control");
                    }
                    
                }
                catch (Exception e){
                 JOptionPane.showMessageDialog(null, e);
                }
                
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_ncontrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ncontrolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ncontrolActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MAlumno al= new MAlumno();
        al.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void b_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_modificarActionPerformed
        txt_nombre.setEnabled(true);
        txt_apaterno.setEnabled(true);
        txt_amaterno.setEnabled(true);
        cmb_turno.setEnabled(true);
        cmb_semestre.setEnabled(true);
        cmb_grupo.setEnabled(true);
        cmb_status.setEnabled(true);
        /*
        ResultSet rs=null;
        Connection con =null;
        stmt=null;
        try{
                    Class.forName("com.mysql.jdbc.Driver");
                    con=DriverManager.getConnection("jdbc:mysql://localhost:3306/udg","root","");
                    //System.out.print("ll");
                    PreparedStatement pst= con.prepareStatement("Update alumno SET NControl=?, NAlumno='"+txt_nombre.getText()+"',APAlumno='"+txt_apaterno.getText()+"',"
                            + "AMAlumno='"+txt_amaterno.getText()+"', TAlumno='"+cmb_turno.getSelectedItem().toString()+"',"
                                    + "SAlumno='"+cmb_semestre.getSelectedItem().toString()+"',"
                                    + "GAlumno='"+cmb_grupo.getSelectedItem().toString()+"', "
                                    + "VAlumno='"+cmb_vigencia.getSelectedItem().toString()+"' "
                                    + "WHERE NControl='"+txt_ncontrol.getText()+"'");  
                   
                    pst.executeUpdate();
                    limpiar();
                    JOptionPane.showMessageDialog(null, "Datos Actualizados");
                    //stmt.setSring(1,txt_ncontrol());
                        
                    
                    
                }
                catch (Exception e){
                 Logger.getLogger(CAlumno.class.getName()).log(Level.SEVERE,null,e);
                }
        */
    }//GEN-LAST:event_b_modificarActionPerformed

    private void cmb_turnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_turnoItemStateChanged
        //ComboBoxModel  c = new ComboBoxModel();
        String opc1[] ={"????","????","????","????"};
        String opc2[] ={"????","????","????","????"};
        String opc3[] ={"SELECCIONAR","1","2","3","4","5","6"};
        String opc4[] ={"SELECCIONAR","A","B",};
        if(cmb_turno.getSelectedItem()=="????"){
            cmb_semestre.removeAllItems();
            cmb_grupo.removeAllItems();
            //System.out.println("dhf");
            for (String s1:opc1){
                cmb_semestre.addItem(s1);
            }
            for (String s2:opc1){
                cmb_grupo.addItem(s2);
            }
            
        }
        else{
            cmb_semestre.removeAllItems();
            cmb_grupo.removeAllItems();
            //System.out.println("dhf");
            for (String s3:opc3){
                cmb_semestre.addItem(s3);
            }
            for (String s4:opc4){
                cmb_grupo.addItem(s4);
            }
        }
        
    }//GEN-LAST:event_cmb_turnoItemStateChanged

    private void cmb_turnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_turnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_turnoActionPerformed

    private void cmb_grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_grupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_grupoActionPerformed

    private void jButton1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyTyped
       
    }//GEN-LAST:event_jButton1KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showConfirmDialog(null, "¿Esta Seguro?","Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/udg","root","");
            PreparedStatement pst= con.prepareStatement("UPDATE alumno SET NControl='"+txt_ncontrol.getText()+"',NAlumno='"+txt_nombre.getText()
                    +"',APAlumno='"+txt_apaterno.getText()+"',AMAlumno='"+txt_amaterno.getText()+"',TAlumno='"+cmb_turno.getSelectedItem().toString()
                    +"',SAlumno='"+cmb_semestre.getSelectedItem().toString()+"',GAlumno='"+cmb_grupo.getSelectedItem().toString()
                    +"',VAlumno='"+cmb_status.getSelectedItem().toString()+"' WHERE NControl='"+txt_ncontrol.getText()+"'");
            pst.executeUpdate();
                txt_ncontrol.setText("");
                txt_nombre.setText("");
                txt_apaterno.setText("");
                txt_amaterno.setText("");
                //txt_nomImg.setText("");
            //pst.setString(5,cmb_turno.getSelectedItem().toString());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CAlumno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_modificar;
    private javax.swing.JComboBox<String> cmb_grupo;
    private javax.swing.JComboBox<String> cmb_semestre;
    private javax.swing.JComboBox<String> cmb_status;
    private javax.swing.JComboBox<String> cmb_turno;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_foto;
    private javax.swing.JTextField txt_amaterno;
    private javax.swing.JTextField txt_apaterno;
    private javax.swing.JTextField txt_ncontrol;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
