package Alumno;

import clases.UPrincipal;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import javax.swing.JOptionPane;
//import java.sql.DriverManager;
//import java.sql.SQLException;
//import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
public class EAlumnos extends javax.swing.JFrame {

    /**
     * Creates new form EAlumnos
     */
    public EAlumnos() {
        initComponents();
        this.setTitle("Agregar Alumnos");
        this.setLocationRelativeTo(null);
        
              Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
      int height = pantalla.height;
      int width = pantalla.width;
      setSize(width/2, height/2);		

      setLocationRelativeTo(null);		
      setVisible(true);
        setLocationRelativeTo(null);
  setSize(900,668);
        setTitle("UDG");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_apaterno = new javax.swing.JTextField();
        txt_ncontrol = new javax.swing.JTextField();
        cmb_turno = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cmb_semestre = new javax.swing.JComboBox<>();
        txt_amaterno = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_alumno = new javax.swing.JTextField();
        cmb_grupo = new javax.swing.JComboBox<>();
        cmb_vigencia = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        selecImg = new javax.swing.JButton();
        txt_nomImg = new javax.swing.JTextField();
        lbl_img = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Numero de control");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 230, 250, 30);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setText("Semestre");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(640, 290, 90, 23);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setText("Turno");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(630, 220, 70, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Alumnos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 20, 110, 29);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setText("Apellido Materno");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 410, 240, 30);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Nombre(s)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 290, 190, 30);

        txt_apaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_apaternoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apaternoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_apaterno);
        txt_apaterno.setBounds(60, 380, 280, 30);

        txt_ncontrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ncontrolActionPerformed(evt);
            }
        });
        txt_ncontrol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_ncontrolKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ncontrolKeyTyped(evt);
            }
        });
        getContentPane().add(txt_ncontrol);
        txt_ncontrol.setBounds(60, 260, 280, 30);

        cmb_turno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "MATUTINO", "VESPERTINO", "????" }));
        cmb_turno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_turnoItemStateChanged(evt);
            }
        });
        cmb_turno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_turnoActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_turno);
        cmb_turno.setBounds(590, 250, 260, 30);

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(770, 570, 81, 25);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setText("Apellido Paterno");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 350, 240, 30);

        cmb_semestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "1", "2", "3", "4", "5", "6" }));
        getContentPane().add(cmb_semestre);
        cmb_semestre.setBounds(590, 310, 260, 30);

        txt_amaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_amaternoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_amaternoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_amaterno);
        txt_amaterno.setBounds(60, 440, 280, 30);

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(670, 570, 85, 25);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setText("Grupo");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(630, 360, 80, 23);

        txt_alumno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_alumnoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_alumnoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_alumno);
        txt_alumno.setBounds(60, 320, 280, 30);

        cmb_grupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "A", "B" }));
        getContentPane().add(cmb_grupo);
        cmb_grupo.setBounds(590, 380, 260, 30);

        cmb_vigencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "Activo", "Inactivo" }));
        cmb_vigencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_vigenciaActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_vigencia);
        cmb_vigencia.setBounds(590, 440, 260, 30);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setText("STATUS");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(630, 420, 70, 23);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setText("Foto");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 470, 150, 30);

        selecImg.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        selecImg.setText("Seleccionar");
        selecImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecImgActionPerformed(evt);
            }
        });
        getContentPane().add(selecImg);
        selecImg.setBounds(60, 530, 110, 20);

        txt_nomImg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nomImgKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nomImg);
        txt_nomImg.setBounds(60, 500, 280, 30);

        lbl_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alumno.png"))); // NOI18N
        lbl_img.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lbl_img);
        lbl_img.setBounds(70, 30, 180, 200);

        fondo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo menu.jpg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, -10, 900, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
           if(txt_ncontrol.getText().equals("")||(txt_alumno.getText().equals(""))||(txt_apaterno.getText().equals(""))||(txt_amaterno.getText().equals(""))){
            javax.swing.JOptionPane.showMessageDialog(this, "Debes llenar todos los campos","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            txt_ncontrol.requestFocus();
            }
           else{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/udg","root","");
           PreparedStatement pst= con.prepareStatement("INSERT INTO alumno (NControl,NAlumno,APAlumno,AMAlumno,TAlumno,SAlumno,GAlumno,VAlumno,nomImagen,imagen) VALUES(?,?,?,?,?,?,?,?,?,?)");
           //PreparedStatement pps=cn.prepareStatement("INSERT INTO calis (NControl,contraseña) VALUES(?,?)");
           FileInputStream archivofoto;
           pst.setString(1,txt_ncontrol.getText());
           pst.setString(2,txt_alumno.getText());
           pst.setString(3,txt_apaterno.getText());
           pst.setString(4,txt_amaterno.getText());
           pst.setString(5,cmb_turno.getSelectedItem().toString());
           pst.setString(6,cmb_semestre.getSelectedItem().toString());
           pst.setString(7,cmb_grupo.getSelectedItem().toString());
           pst.setString(8,cmb_vigencia.getSelectedItem().toString());
           pst.setString(9,txt_nomImg.getText());
           archivofoto=new FileInputStream(txt_nomImg.getText());
           pst.setBinaryStream(10, archivofoto);
           pst.executeUpdate();
           //ResultSet rs=pst.executeUpdate()
               JOptionPane.showMessageDialog(null,"Se guardaron los datos correctamente");
               MAlumno p1= new MAlumno();
               p1.setVisible(true);
               this.dispose();
               txt_ncontrol.setText("");
               txt_alumno.setText("");
               txt_apaterno.setText("");
               txt_amaterno.setText("");
               txt_nomImg.setText("");
               
           }
           
       }
       catch (Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
       
    



       //Entradas ent= new Entradas();
       //ent.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_ncontrolKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ncontrolKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9')evt.consume();
        if (txt_ncontrol.getText().length()>8)evt.consume();
        
    }//GEN-LAST:event_txt_ncontrolKeyTyped

    private void txt_alumnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_alumnoKeyTyped
        //char c = evt.getKeyChar();
        //if ((c<'A' || c>'Z') && (c!=' '))evt.consume();
       
    }//GEN-LAST:event_txt_alumnoKeyTyped

    private void txt_apaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apaternoKeyTyped
       // char c = evt.getKeyChar();
       // if ((c<'A' || c>'Z') && (c!=' '))evt.consume();
    }//GEN-LAST:event_txt_apaternoKeyTyped

    private void txt_amaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_amaternoKeyTyped
       // char c = evt.getKeyChar();
       // if ((c<'A' || c>'Z') && (c!=' '))evt.consume();
    }//GEN-LAST:event_txt_amaternoKeyTyped

    private void txt_ncontrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ncontrolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ncontrolActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MAlumno p1= new MAlumno();
        p1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmb_vigenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_vigenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_vigenciaActionPerformed

    private void txt_nomImgKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomImgKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomImgKeyTyped

    private void selecImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecImgActionPerformed
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formatos de Archivos JPEG(*.JPG;.JPEG)","jpg","jpeg");
        JFileChooser archivo = new JFileChooser();
        archivo.addChoosableFileFilter(filtro);
        archivo.setDialogTitle("Abrir Imagen");
        File ruta = new File("C:\\Users\\jose6\\OneDrive\\Documentos\\Imagenes");
        archivo.setCurrentDirectory(ruta);
        int ventana = archivo.showOpenDialog(null);
        if (ventana == JFileChooser.APPROVE_OPTION){
            File file = archivo.getSelectedFile();
            txt_nomImg.setText(String.valueOf(file));
            Image foto= getToolkit().getImage(txt_nomImg.getText());
            //ImageIcon icon = new ImageIcon(getClass().getResource(url));
            int ancho= lbl_img.getWidth();
            int alto= lbl_img.getHeight();
            //ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
            lbl_img.setIcon(new ImageIcon(foto.getScaledInstance(ancho, alto, Image.SCALE_DEFAULT)));
        }
            
    }//GEN-LAST:event_selecImgActionPerformed

    private void cmb_turnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_turnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_turnoActionPerformed

    private void cmb_turnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_turnoItemStateChanged
        String opc1[] ={"????","????","????","????"};
        String opc2[] ={"????","????","????","????"};
        String opc3[] ={"SELECCIONAR","1","2","3","4","5","6"};
        String opc4[] ={"SELECCIONAR","A","B",};
        if(cmb_turno.getSelectedItem()=="????"){
            cmb_semestre.removeAllItems();
            cmb_grupo.removeAllItems();
            
            for (String s1:opc1){
                cmb_semestre.addItem(s1);
            }
            for (String s2:opc1){
                cmb_grupo.addItem(s2);
            }
            
        }
        else{
            cmb_semestre.removeAllItems();
            cmb_grupo.removeAllItems();
            
            for (String s3:opc3){
                cmb_semestre.addItem(s3);
            }
            for (String s4:opc4){
                cmb_grupo.addItem(s4);
            }
        }
    }//GEN-LAST:event_cmb_turnoItemStateChanged

    private void txt_ncontrolKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ncontrolKeyReleased
        
        String cadena= (txt_ncontrol.getText()).toUpperCase();
        txt_ncontrol.setText(cadena);
    }//GEN-LAST:event_txt_ncontrolKeyReleased

    private void txt_alumnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_alumnoKeyReleased
        // TODO add your handling code here:
        String cadena= (txt_alumno.getText()).toUpperCase();
        txt_alumno.setText(cadena);
    }//GEN-LAST:event_txt_alumnoKeyReleased

    private void txt_apaternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apaternoKeyReleased
        String cadena= (txt_apaterno.getText()).toUpperCase();
        txt_apaterno.setText(cadena);
    }//GEN-LAST:event_txt_apaternoKeyReleased

    private void txt_amaternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_amaternoKeyReleased
        String cadena= (txt_amaterno.getText()).toUpperCase();
        txt_amaterno.setText(cadena);
    }//GEN-LAST:event_txt_amaternoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmb_grupo;
    private javax.swing.JComboBox<String> cmb_semestre;
    private javax.swing.JComboBox<String> cmb_turno;
    private javax.swing.JComboBox<String> cmb_vigencia;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JButton selecImg;
    private javax.swing.JTextField txt_alumno;
    private javax.swing.JTextField txt_amaterno;
    private javax.swing.JTextField txt_apaterno;
    private javax.swing.JTextField txt_ncontrol;
    private javax.swing.JTextField txt_nomImg;
    // End of variables declaration//GEN-END:variables
}
