/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import javax.swing.JOptionPane;
//import java.sql.DriverManager;
//import java.sql.SQLException;
//import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import java.sql.*;
import javax.swing.InputMap;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
/**
 *
 * @author jose6
 */
public class MeVigilante extends javax.swing.JFrame {
    String msj1,msj2;
    Statement stmt=null;
    /**
     * Creates new form MeVigilante
     */
    public MeVigilante() {
        initComponents();
        this.setTitle("Vigilante");
        this.setLocationRelativeTo(null);
        
              Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
      int height = pantalla.height;
      int width = pantalla.width;
      setSize(width/2, height/2);		

      setLocationRelativeTo(null);		
      setVisible(true);
        setLocationRelativeTo(null);
        setSize(900,668);
        setTitle("UDG");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_apaterno = new javax.swing.JTextField();
        NC = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmb_turno = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmb_grupo = new javax.swing.JComboBox<>();
        cmb_semestre = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmb_vigencia = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_amaterno = new javax.swing.JTextField();
        txt_ncontrol = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Numero de control");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 130, 147, 76);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Nombre");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(640, 140, 147, 76);

        txt_apaterno.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        getContentPane().add(txt_apaterno);
        txt_apaterno.setBounds(50, 410, 280, 30);

        NC.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        NC.setText("Numero de Control");
        getContentPane().add(NC);
        NC.setBounds(60, 250, 260, 20);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setText("Vigencia");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(640, 440, 210, 30);

        cmb_turno.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmb_turno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "MATUTINO", "VESPERTINO", "????" }));
        cmb_turno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_turnoItemStateChanged(evt);
            }
        });
        cmb_turno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_turnoActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_turno);
        cmb_turno.setBounds(530, 270, 310, 30);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setText("Semestre");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(640, 310, 210, 20);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setText("Turno");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(650, 240, 190, 20);

        txt_nombre.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        getContentPane().add(txt_nombre);
        txt_nombre.setBounds(50, 350, 270, 30);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setText("Grupo");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(630, 370, 200, 40);

        cmb_grupo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmb_grupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "A", "B" }));
        getContentPane().add(cmb_grupo);
        cmb_grupo.setBounds(540, 400, 300, 30);

        cmb_semestre.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmb_semestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "1", "2", "3", "4", "5", "6" }));
        getContentPane().add(cmb_semestre);
        cmb_semestre.setBounds(540, 340, 300, 30);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setText("Apellido Materno");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 440, 250, 30);

        cmb_vigencia.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmb_vigencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "Activo", "Inactivo" }));
        getContentPane().add(cmb_vigencia);
        cmb_vigencia.setBounds(540, 470, 300, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Consultar");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 40, 210, 40);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setText("Apellido Paterno");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 380, 240, 30);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 320, 200, 20);

        txt_amaterno.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        getContentPane().add(txt_amaterno);
        txt_amaterno.setBounds(50, 480, 280, 30);

        txt_ncontrol.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txt_ncontrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ncontrolActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ncontrol);
        txt_ncontrol.setBounds(50, 280, 270, 30);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo menu.jpg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 900, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ResultSet rs=null;

        msj1=JOptionPane.showInputDialog(this, "Numero de control","Consultar alumno",JOptionPane.QUESTION_MESSAGE);
        String sql="SELECT * FROM alumno WHERE NControl ='"+msj1+"'";
        //String sql1="Select * from calis where usuario=? and contra=?";

        if (msj1==null)
        JOptionPane.showMessageDialog(this, "La opcion fue cancelada","Aviso!",JOptionPane.INFORMATION_MESSAGE);
        else{
            if(msj1.equals("")){
                JOptionPane.showMessageDialog(this, "Ingrese el NUMERO DE CONTROL del alumno que desea consultar","Aviso!",JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/udg","root","");
                    stmt=con.createStatement();
                    rs=stmt.executeQuery(sql);
                    if (rs.next()){
                        txt_ncontrol.setText(rs.getString("NControl"));
                        txt_nombre.setText(rs.getString("NAlumno"));
                        txt_apaterno.setText(rs.getString("APAlumno"));
                        txt_amaterno.setText(rs.getString("AMAlumno"));
                        cmb_turno.setSelectedItem(rs.getString("TAlumno"));
                        cmb_semestre.setSelectedItem(rs.getString("SAlumno"));
                        cmb_grupo.setSelectedItem(rs.getString("GAlumno"));
                        cmb_vigencia.setSelectedItem(rs.getString("VAlumno"));
                    }
                    else {
                        JOptionPane.showMessageDialog(null,"No existe ese numero de control");
                    }

                }
                catch (Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_ncontrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ncontrolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ncontrolActionPerformed

    private void cmb_turnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_turnoItemStateChanged
        //ComboBoxModel  c = new ComboBoxModel();
        String opc1[] ={"????","????","????","????"};
        String opc2[] ={"????","????","????","????"};
        String opc3[] ={"SELECCIONAR","1","2","3","4","5","6"};
        String opc4[] ={"SELECCIONAR","A","B",};
        if(cmb_turno.getSelectedItem()=="????"){
            cmb_semestre.removeAllItems();
            cmb_grupo.removeAllItems();
            System.out.println("dhf");
            for (String s1:opc1){
                cmb_semestre.addItem(s1);
            }
            for (String s2:opc1){
                cmb_grupo.addItem(s2);
            }

        }
        else{
            cmb_semestre.removeAllItems();
            cmb_grupo.removeAllItems();
            System.out.println("dhf");
            for (String s3:opc3){
                cmb_semestre.addItem(s3);
            }
            for (String s4:opc4){
                cmb_grupo.addItem(s4);
            }
        }

    }//GEN-LAST:event_cmb_turnoItemStateChanged

    private void cmb_turnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_turnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_turnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeVigilante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeVigilante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeVigilante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeVigilante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeVigilante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NC;
    private javax.swing.JComboBox<String> cmb_grupo;
    private javax.swing.JComboBox<String> cmb_semestre;
    private javax.swing.JComboBox<String> cmb_turno;
    private javax.swing.JComboBox<String> cmb_vigencia;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_amaterno;
    private javax.swing.JTextField txt_apaterno;
    private javax.swing.JTextField txt_ncontrol;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
